// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8C570NwDrHs736gzoelL0PaPty6fXPz4',
    appId: '1:388276208544:web:6278987c945cc129855ac5',
    messagingSenderId: '388276208544',
    projectId: 'wibubarber',
    authDomain: 'wibubarber.firebaseapp.com',
    storageBucket: 'wibubarber.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvG0Tuuxx98vkZyycA6m6mmcPK9-7Aj2g',
    appId: '1:388276208544:android:32f3805abbbb4e9c855ac5',
    messagingSenderId: '388276208544',
    projectId: 'wibubarber',
    storageBucket: 'wibubarber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgNfPG6A_ogM02Wc1xCbUOdF87UJnK8s',
    appId: '1:388276208544:ios:106a0fef50037b31855ac5',
    messagingSenderId: '388276208544',
    projectId: 'wibubarber',
    storageBucket: 'wibubarber.appspot.com',
    iosClientId: '388276208544-n9rps1sotv019gisjfpa5ssa9e5qddt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wibubarber',
  );
}
